# Generated by Django 4.2.8 on 2024-09-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_usuario_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje Total'),
        ),
    ]
