# Generated by Django 4.2.8 on 2024-09-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_usuario_puntaje_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentos',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.usuario'),
        ),
    ]
