# Generated by Django 4.2.8 on 2024-09-08 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_alter_intentos_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elegir',
            new_name='ElegirRespuesta',
        ),
        migrations.RenameModel(
            old_name='Intentos',
            new_name='PreguntasRespondidas',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='QuizUsuario',
        ),
    ]
